### ISSUE TITLE
matchOrders for more than 2 orders?

### ISSUE THREAD

**Issue by WyseNynja** [0xProject/0x-protocol-specification#10]
I'm upgrading some code I wrote for v1 to v2 and am planning to make use of the matchOrders function. It works for 2-currency arbitrage opportunities, but I've seen some times where 3 orders between 3 different assets can all fill each other. Would it be possible to expand matchOrders to accept more than 2 orders? What would that involve?

It would be awesome to be able to execute triangular arbitrage without needing any tokens besides eth for gas, but if expanding matchOrders is not simple/possible, how would you recommend filling 3 or more orders in one eth transaction? I think [batchFillOrKillOrders](https://github.com/0xProject/0x-protocol-specification/blob/master/v2/v2-specification.md#batchfillorkillorders) is what I should use, but that requires that I have tokens for the first order that can't come from the last order.

I asked about this and more [on r/0xProject](https://www.reddit.com/r/0xProject/comments/9uhcl9/atomic_arbitrage/).

**Comment by abandeali1** [comment]
Currently `matchOrders` only supports matching 2 orders. We will likely extend this to support an arbitrary number of orders in v2.1/v3.0, but the implementation is much more difficult. You are correct that the easiest way to do this is right now is with `batchFillOrKillOrders` and something like marble to provide the initial liquidity (they have an example contract [here](https://github.com/marbleprotocol/flash-lending/blob/master/contracts/example/Arbitrage.sol). You can use something like DSProxy as well, but I'd think you would want to write a custom contract for gas efficiency reasons.
